"""add post's attachment

Revision ID: 2a8d4dbfbaff
Revises: 639701c846ad
Create Date: 2022-01-27 15:56:29.768529

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2a8d4dbfbaff'
down_revision = '639701c846ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('attachment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_attachment_id'), 'post', ['attachment_id'], unique=False)
    op.create_foreign_key(None, 'post', 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_attachment_id'), table_name='post')
    op.drop_column('post', 'attachment_id')
    # ### end Alembic commands ###
