"""add user.disabled_at

Revision ID: 36908edbe6c9
Revises: 9f5a972a21b2
Create Date: 2021-12-20 15:16:08.417874

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '36908edbe6c9'
down_revision = '9f5a972a21b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled_at')
    # ### end Alembic commands ###
