"""add search index on user

Revision ID: 4dcd7b00de90
Revises: a877e1f884be
Create Date: 2021-12-26 21:29:15.470060

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "4dcd7b00de90"
down_revision = "a877e1f884be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_search_user_tsv", "user", [sa.text("to_tsvector('french', firstname || lastname)")], postgresql_using="gin"
    )  # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search__user_tsv")
    # ### end Alembic commands ###
