"""add posts

Revision ID: 639701c846ad
Revises: 4dcd7b00de90
Create Date: 2022-01-26 17:45:20.498819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '639701c846ad'
down_revision = '4dcd7b00de90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('communication', 'culture', 'personal_development', 'emotional_intelligence', 'hobbie', 'professional_world', 'parenting', 'quality_of_life', 'search_of_meaning', 'physical_health', 'spirituality', 'emotional_life', name='postcategorie'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('related_to_itself', sa.Boolean(), nullable=True),
    sa.Column('related_to_spouse', sa.Boolean(), nullable=True),
    sa.Column('related_to_familly', sa.Boolean(), nullable=True),
    sa.Column('related_to_work', sa.Boolean(), nullable=True),
    sa.Column('related_to_friend_and_community', sa.Boolean(), nullable=True),
    sa.Column('related_to_everyone', sa.Boolean(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('\n            related_to_itself OR\n            related_to_spouse OR\n            related_to_familly OR\n            related_to_work OR\n            related_to_friend_and_community OR\n            related_to_everyone = TRUE\n            '),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_author_id'), 'post', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_content'), 'post', ['content'], unique=False)
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_index(op.f('ix_post_related_to_everyone'), 'post', ['related_to_everyone'], unique=False)
    op.create_index(op.f('ix_post_related_to_familly'), 'post', ['related_to_familly'], unique=False)
    op.create_index(op.f('ix_post_related_to_friend_and_community'), 'post', ['related_to_friend_and_community'], unique=False)
    op.create_index(op.f('ix_post_related_to_itself'), 'post', ['related_to_itself'], unique=False)
    op.create_index(op.f('ix_post_related_to_spouse'), 'post', ['related_to_spouse'], unique=False)
    op.create_index(op.f('ix_post_related_to_work'), 'post', ['related_to_work'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_table('user_have_post_in_favorite',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', 'deleted_at')
    )
    op.create_index(op.f('ix_user_have_post_in_favorite_id'), 'user_have_post_in_favorite', ['id'], unique=False)
    op.create_index(op.f('ix_user_have_post_in_favorite_post_id'), 'user_have_post_in_favorite', ['post_id'], unique=False)
    op.create_index(op.f('ix_user_have_post_in_favorite_user_id'), 'user_have_post_in_favorite', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_have_post_in_favorite_user_id'), table_name='user_have_post_in_favorite')
    op.drop_index(op.f('ix_user_have_post_in_favorite_post_id'), table_name='user_have_post_in_favorite')
    op.drop_index(op.f('ix_user_have_post_in_favorite_id'), table_name='user_have_post_in_favorite')
    op.drop_table('user_have_post_in_favorite')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_related_to_work'), table_name='post')
    op.drop_index(op.f('ix_post_related_to_spouse'), table_name='post')
    op.drop_index(op.f('ix_post_related_to_itself'), table_name='post')
    op.drop_index(op.f('ix_post_related_to_friend_and_community'), table_name='post')
    op.drop_index(op.f('ix_post_related_to_familly'), table_name='post')
    op.drop_index(op.f('ix_post_related_to_everyone'), table_name='post')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_index(op.f('ix_post_content'), table_name='post')
    op.drop_index(op.f('ix_post_author_id'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
