"""add disabled_add to user

Revision ID: 74007f075d2d
Revises: f501437809d2
Create Date: 2021-12-21 09:52:21.110355

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '74007f075d2d'
down_revision = 'f501437809d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled_at')
    # ### end Alembic commands ###
