"""add phone number

Revision ID: a2b3dcf59be9
Revises: eaa78eede38e
Create Date: 2021-12-22 14:21:18.863498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a2b3dcf59be9'
down_revision = 'eaa78eede38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_unique_constraint(None, 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
