"""add type on user

Revision ID: a877e1f884be
Revises: efe87f656855
Create Date: 2021-12-26 13:25:23.462444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql    
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a877e1f884be'
down_revision = 'efe87f656855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    usertype = postgresql.ENUM('user', 'moderator', 'admin', name='usertype')
    usertype.create(op.get_bind())
    op.add_column('user', sa.Column('type', sa.Enum('user', 'moderator', 'admin', name='usertype'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    usertype = postgresql.ENUM('user', 'moderator', 'admin', name='usertype')
    usertype.create(op.get_bind())
    # ### end Alembic commands ###
