"""add attachment

Revision ID: f501437809d2
Revises: 36908edbe6c9
Create Date: 2021-12-21 09:19:13.824920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f501437809d2'
down_revision = '36908edbe6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_attachment_filename'), 'attachment', ['filename'], unique=False)
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=False)
    op.create_index(op.f('ix_attachment_name'), 'attachment', ['name'], unique=False)
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_avatar_id'), 'user', ['avatar_id'], unique=False)
    op.create_foreign_key(None, 'user', 'attachment', ['avatar_id'], ['id'])
    op.drop_column('user', 'disabled_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_avatar_id'), table_name='user')
    op.drop_column('user', 'avatar_id')
    op.drop_column('user', 'deleted_at')
    op.drop_index(op.f('ix_attachment_name'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_filename'), table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
